### ISSUE TITLE
few improvements for developing experience

### ISSUE THREAD

**Issue by cclien0725** [Largeb0525/futil#2]
Hi, this is Joseph from KKCompany.

Thanks for taking time for the test. It's great to see you integrate the ci pipeline in the development lifecycle. It'll be nice if use the lint tool/security checker which can fail fast to find the possible issues in the local or ci pipeline. For further improvement can consider introducing the checker e.g. [golangci-lint](https://github.com/golangci/golangci-lint) within the local pre-commit hook or ci pipeline.

**Comment by Largeb0525** [comment]
add golangci-lint
https://github.com/Largeb0525/futil/commit/20ee7fb1331d2b0916637eb1803fc4b850199171
